export const refs = {
  form: document.querySelector('.search-form'),
  movieContainer: document.querySelector('.films__gallery'),
  movieOneCardContainer: document.querySelector('.films__gallery'),
  cardModalMovie: document.querySelector('.js-modal-card'), //на один фильм
  backdropMovie: document.querySelector('.movie-backdrop'),
  closeBtn: document.querySelector('.video__close-icon'),
  modalWindowBehind: document.querySelector('.modal__card'),
  videoIframe: document.querySelector('#player'),
  playBtn: document.querySelector('.modal__play-bacground'),
  btnAutorization: document.querySelector('.auth-btn'),
  btnRegistration: document.querySelector('.regist-btn'),
  formAutorization: document.querySelector('.form-authorization'),
  formRegistration: document.querySelector('.form-register'),
  scrollEl: document.querySelector('.js-scroll'),
  closeModalBtn: document.querySelector('.js-close-button'),
  modal: document.querySelector('.js-backdrop'),
  body: document.querySelector('body'),
  toggle: document.querySelector('.toggle-input'),
  footer: document.querySelector('footer'),
};
